#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.2.9f1_ebce4d76e6e8"
#define UNITY_VERSION_FULL_NICE "2019.2.9f1 (ebce4d76e6e8)"
#define UNITY_VERSION_BLD 15453773
#define UNITY_VERSION_DATE 1570152819
#define UNITY_VERSION_WIN "2019.2.9.15453773"
#define UNITY_VERSION_BRANCH "2019.2/staging"
